### ISSUE TITLE
Failed prop type: Invalid props.style.key 'textAlign' supplied to 'View'

### ISSUE THREAD

**Issue by gunterberger** [xinghui0000/react-native-progress-button#1]
As soon as I press a button, I get the following Error: "Failed prop type: Invalid props.style.key 'textAlign' supplied to 'View'"

**Comment by xinghui0000** [comment]
@gunterberger  Hi, thanks for the report , I will take a look.
this error occurred in the Example?

**Comment by gunterberger** [comment]
Not to worry, I managed to build my own component.

**Comment by xinghui0000** [comment]
OK，thanks
